#!/bin/bash
export pki_ca_type="intermediate"
export pki_dir="$(pwd)/${pki_ca_type}"
export pki_policy=loose

mkdir -p bundles

mkdir -p ${pki_dir}/{certs,csr,crl,newcerts,private}
chmod 700 ${pki_dir}/private
touch ${pki_dir}/index.txt
echo "unique_subject = no" > ${pki_dir}/index.txt.attr
echo 1000 > ${pki_dir}/serial

openssl req \
  -config ./openssl.cnf \
  -sha512 \
  -nodes \
  -newkey rsa:4096 \
  -days 3650 \
  -keyout ${pki_dir}/private/${pki_ca_type}.key.pem \
  -out ${pki_dir}/csr/${pki_ca_type}.csr.pem \
  -subj "/C=GB/O=Security/OU=Research/CN=demoSigningCA"

export pki_ca_type="ca"
export pki_dir="$(pwd)/${pki_ca_type}"
export pki_policy=strict

openssl ca \
      -batch \
      -config ./openssl.cnf \
      -extensions v3_intermediate_ca \
      -days 3650 -notext -md sha256 \
      -in intermediate/csr/intermediate.csr.pem \
      -out intermediate/certs/intermediate.cert.pem

